In [2]:
# Reference
# [1] https://www.jfa.jp/samuraiblue/worldcup_2022/squad/
# [2] https://www.transfermarkt.co.uk/

# This program draws;
# a. the relation between
#    (X) market value at 2022/12/06, during the FIFA World Cup 2022, and
#    (Y) market value at 2022/07/10, after the FIFA World Cup 2022
# of the Japan national football team members called up for the FIFA World Cup

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('../input/20230711_football_market_value.csv')

def numerize(s:str) -> int:
    if 'k' in s:
        unit = 10**3
    elif 'm' in s:
        unit = 10**6
    
    num = float( s.replace('k','').replace('m','') )

    return int(num * unit)

df['20221206-MarketValue'] = df['20221206-MarketValue'].apply(numerize)
df['20230710-MarketValue'] = df['20230710-MarketValue'].apply(numerize)
df

,Position,No,Name,Birthday,20221206-Club,20221206-MarketValue,20230710-Club,20230710-MarketValue
0,GK,1,KAWASHIMA Eiji,1983-03-20,Strasbourg,200000,Strasbourg,150000
1,GK,12,GONDA Shuichi,1989-03-03,Shimizu S-Pulse,500000,Shimizu S-Pulse,400000
2,GK,23,SCHMIDT Daniel,1992-02-03,Sint-Truiden,1500000,Sint-Truiden,1500000
3,DF,2,YAMANE Miki,1993-12-22,Kawasaki Frontale,1700000,Kawasaki Frontale,1600000
4,DF,3,TANIGUCHI Shogo,1991-07-15,Kawasaki Frontale,1800000,Al-Rayyan,1500000
5,DF,4,ITAKURA Ko,1997-01-27,Borussia Mönchengladbach,7500000,Borussia Mönchengladbach,12000000
6,DF,5,NAGATOMO Yuto,1986-09-12,FC Tokyo,400000,FC Tokyo,300000
7,DF,16,TOMIYASU Takehiro,1998-11-05,Arsenal,25000000,Arsenal,25000000
8,DF,19,SAKAI Hiroki,1990-04-12,Urawa Red Diamonds,1700000,Urawa Red Diamonds,1400000
9,DF,22,YOSHIDA Maya,1988-08-24,Schalke 04,1500000,Schalke 04,900000
10,DF,26,ITO Hiroki,1999-05-12,VfB Stuttgart,5500000,VfB Stuttgart,10000000
11,MF,6,ENDO Wataru,1993-02-09,VfB Stuttgart,6500000,VfB Stuttgart,6500000
12,MF,7,SHIBASAKI Gaku,1992-05-28,Leganés,1000000,Leganés,1000000
13,MF,8,DOAN Ritsu,1998-06-16,SC Freiburg,12000000,SC Freiburg,18000000
14,MF,9,MITOMA Kaoru,1997-05-20,Brighton & Hove Albion,6000000,Brighton & Hove Albion,32000000
15,MF,10,MINAMINO Takumi,1995-01-16,Monaco,10000000,Monaco,6000000
16,MF,11,KUBO Takefusa,2001-06-04,Real Sociedad,12000000,Real Sociedad,25000000
17,MF,13,MORITA Hidemasa,1995-05-10,Sporting CP,7000000,Sporting CP,12000000
18,MF,14,ITO Junya,1993-03-09,Reims,9000000,Reims,10000000
19,MF,15,KAMADA Daichi,1996-08-05,Eintracht Frankfurt,30000000,Eintracht Frankfurt,27000000
20,MF,17,TANAKA Ao,1998-09-10,Fortuna Düsseldorf,1800000,Fortuna Düsseldorf,2500000
21,MF,24,SOMA Yuki,1997-02-25,Nagoya Grampus,1200000,Casa Pia,1200000
22,FW,18,ASANO Takuma,1994-11-10,\tVfL Bochum,3000000,\tVfL Bochum,4000000
23,FW,20,MACHINO Shuto,1999-09-30,Shonan Bellmare,1200000,Holstein Kiel,1500000
24,FW,21,UEDA Ayase,1998-08-28,Cercle Brugge,2000000,Cercle Brugge,6000000
25,FW,25,MAEDA Daizen,1997-10-20,Celtic,4000000,Celtic,6000000

In [9]:
fig = plt.figure(figsize=(10,10))
# plt.subplots_adjust(left=0.2,right=0.8,top=0.9)
plt.style.use('dark_background')
plt.rcParams['font.size'] = 15
# plt.xscale('log')
# plt.yscale('log')
plt.xlim(0.0*10**6,33*10**6)
plt.ylim(0.0*10**6,33*10**6)
plt.xlabel("Market Value (2022/12/06)",alpha=0.8)
plt.ylabel("Market Value (2023/07/10)",alpha=0.8)
ticks = [i*10**6 for i in range(0,33+1) if i%5==0]
labels = ['0'] + [f'€{i:,}M' for i in range(1,33+1) if i%5==0]
plt.xticks(ticks=ticks, labels=labels,rotation=90,alpha=0.8)
plt.yticks(ticks=ticks, labels=labels,alpha=0.8)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
plt.title("Market Value Changes of Japan National Football Players\nBefore and After FIFA World Cup 2022")

for i in range(0,33+1):
    plt.axvline(x=i*10**6,color="white",alpha=0.3,linewidth=1)
    plt.axhline(y=i*10**6,color="white",alpha=0.3,linewidth=1)
    if i%5==0:
        plt.axvline(x=i*10**6,color="white",alpha=0.6,linewidth=1)
        plt.axhline(y=i*10**6,color="white",alpha=0.6,linewidth=1)

plt.plot([i*10**6 for i in range(0,33+1)],[i*10**6 for i in range(0,33+1)],c='white',alpha=0.3)
plt.scatter(df['20221206-MarketValue'],df['20230710-MarketValue'],s=10*3,c='white')

name_legend = {
    'ITAKURA Ko':       [ 0.1, 0.1],
    'TOMIYASU Takehiro':[ 0.1, 0.1],
    'ITO Hiroki':       [-2.1, 0.1],
    'ENDO Wataru':      [ 0.1, 0.1],
    'DOAN Ritsu':       [ 0.1, 0.1],
    'MITOMA Kaoru':     [ 0.1, 0.1],
    'MINAMINO Takumi':  [ 0.1,-1.0],
    'KUBO Takefusa':    [ 0.1, 0.1],
    'MORITA Hidemasa':  [-2.9, 0.1],
    'ITO Junya':        [ 0.1, 0.1],
    'KAMADA Daichi':    [ 0.1, 0.1],
    'TANAKA Ao':        [-3.2, 0.1],
    'ASANO Takuma':     [ 0.1,-1.0],
    'UEDA Ayase':       [-2.3, 0.1],
    'MAEDA Daizen':     [-0.1,-1.0],
}
for name,x,y in df[['Name','20221206-MarketValue','20230710-MarketValue']].values:
    if name in name_legend:
        n1,n2 = name.split(' ')
        n = f'{n2[0]}.{n1.capitalize()}' if n1 in ['ITO'] else n1.capitalize()
        _x,_y=name_legend[name]
        plt.text(x+_x*10**6,y+_y*10**6,n,color='white',fontsize=15)

fig.savefig("../output/20230711_Football_Market_Value.png")
plt.close()